name: Landing

on:
  push:
    branches:
      - main

jobs:
  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
      - name: install modules
        run: npm i
      - name: build landing
        run: npm run build
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_LANDING_HOST }}
          username: ${{ secrets.LANDING_USER }}
          key: ${{ secrets.MATJAR_LANDING_SECRET }}
          script: sh scripts/deploy_landing.sh

      - name: Print Message
        run: echo "Workflow completed successfully!"

