name: Landing

on:
  push:
    branches:
      - main

jobs:
  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
      - name: INSTALL NODE MODULES
        run: npm i
      - name: BUILD PROJECT
        run: npm run build
      - name: INSTALL SSH KEY
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SECRET }}
          known_hosts: "unnecessary"
      - name: ADDING KNOWS KEYS
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: MOVE BUILD FILES TO THE SERVER
        run: rsync -avz -e "ssh -p ${{ secrets.PORT }}" ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/root/matjarbot-landing-page/

      - name: RESTART THE PM2 SERVER
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET }}
          script: |
            pm2 restart landing

