name: Landing

on:
  push:
    branches:
      - main
jobs:
  pm2-configuration:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
      - name: install modules
        run: npm i
      - name: build landing
        run: npm run build
      - name: serve landing
        run: pm2 start npm --  start
      - name: rename landing in pm2
        run: pm2 restart npm --name landing
